export const MODEL_MAP: Record<string, string> = {
  akkadian: 'PLACEHOLDER_AKKADIAN_MODEL',
  filipino: 'Helsinki-NLP/opus-mt-tl-en',
  french: 'Helsinki-NLP/opus-mt-fr-en',
  spanish: 'Helsinki-NLP/opus-mt-es-en',
  japanese: 'Helsinki-NLP/opus-mt-ja-en',
  arabic: 'Helsinki-NLP/opus-mt-ar-en',
};

export const LANGUAGES = [
  {
    id: 'akkadian',
    name: 'Akkadian',
    subtitle: 'Old Assyrian',
    flag: '𒀭',
    family: 'Semitic (East)',
    speakers: 'Extinct (~2000 BCE – 100 CE)',
    script: 'Cuneiform',
    difficulty: 5,
    difficultyReason: 'Extremely low-resource, complex morphology, damaged texts',
    funFact: 'These tablets are the Instagram stories of the Bronze Age — merchants writing about debts, caravans, and family drama.',
    color: 'from-amber-700 to-amber-900',
  },
  {
    id: 'filipino',
    name: 'Filipino',
    subtitle: 'Tagalog',
    flag: '🇵🇭',
    family: 'Austronesian',
    speakers: '~82 million',
    script: 'Latin (formerly Baybayin)',
    difficulty: 3,
    difficultyReason: 'Verb-initial word order and complex affixation challenge standard models',
    funFact: 'Filipino has borrowed words from Spanish, English, Chinese, Arabic, and Sanskrit.',
    color: 'from-blue-600 to-red-600',
  },
  {
    id: 'french',
    name: 'French',
    subtitle: 'Français',
    flag: '🇫🇷',
    family: 'Romance (Indo-European)',
    speakers: '~321 million',
    script: 'Latin alphabet',
    difficulty: 2,
    difficultyReason: "Tons of training data, but gendered nouns and liaisons add complexity",
    funFact: "For 300 years, French was the official language of England's royal court.",
    color: 'from-blue-700 to-red-600',
  },
  {
    id: 'spanish',
    name: 'Spanish',
    subtitle: 'Español',
    flag: '🇪🇸',
    family: 'Romance (Indo-European)',
    speakers: '~559 million',
    script: 'Latin alphabet',
    difficulty: 1,
    difficultyReason: 'One of the best-resourced languages for AI with massive parallel corpora',
    funFact: 'Spanish has ~4,000 words borrowed from Arabic due to 800 years of Moorish rule.',
    color: 'from-red-600 to-yellow-500',
  },
  {
    id: 'japanese',
    name: 'Japanese',
    subtitle: '日本語',
    flag: '🇯🇵',
    family: 'Japonic',
    speakers: '~125 million',
    script: 'Kanji + Hiragana + Katakana',
    difficulty: 4,
    difficultyReason: 'Three writing systems, no spaces between words, and SOV word order',
    funFact: "Japanese has different levels of politeness built into its grammar — the same sentence changes completely based on who you're talking to.",
    color: 'from-red-600 to-white',
  },
  {
    id: 'arabic',
    name: 'Arabic',
    subtitle: 'العربية',
    flag: '🇸🇦',
    family: 'Semitic (Central)',
    speakers: '~422 million',
    script: 'Arabic script (right-to-left)',
    difficulty: 4,
    difficultyReason: 'Right-to-left script, root-based morphology, and written without most vowels',
    funFact: 'Arabic and Akkadian are distant cousins in the same Semitic language family — separated by 4,000 years.',
    color: 'from-green-700 to-green-900',
  },
];

export const EXAMPLE_PHRASES: Record<string, Array<{ source: string; translation: string }>> = {
  akkadian: [
    { source: 'um-ma A-šùr-i-mì-tí-ma a-na Ṣú-ḫa-a-a qí-bi-ma', translation: 'Thus says Ashur-imitti: speak to Tsukhaya' },
    { source: '1 ma-na KÙ.BABBAR ṣa-ru-pá-am', translation: '1 mina of refined silver' },
    { source: 'a-na ha-ra-nim ú-ṣé-er', translation: 'send on the caravan' },
    { source: 'KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM', translation: 'Seal of Mannum-balum-Aššur son of Ṣilli-Adad' },
    { source: '10 TÚG ku-ta-ni SIG₅', translation: '10 fine kutānum-textiles' },
  ],
  filipino: [
    { source: 'Magandang umaga', translation: 'Good morning' },
    { source: 'Salamat po', translation: 'Thank you (polite)' },
    { source: 'Kumusta ka?', translation: 'How are you?' },
    { source: 'Mahal kita', translation: 'I love you' },
  ],
  french: [
    { source: 'Bonjour le monde', translation: 'Hello world' },
    { source: 'Comment allez-vous?', translation: 'How are you?' },
    { source: "Je m'appelle Charles", translation: 'My name is Charles' },
    { source: 'Merci beaucoup', translation: 'Thank you very much' },
  ],
  spanish: [
    { source: 'Hola, ¿cómo estás?', translation: 'Hello, how are you?' },
    { source: 'Buenos días', translation: 'Good morning' },
    { source: 'Me llamo Carlos', translation: 'My name is Carlos' },
    { source: 'Muchas gracias', translation: 'Thank you very much' },
  ],
  japanese: [
    { source: 'こんにちは', translation: 'Hello' },
    { source: 'ありがとうございます', translation: 'Thank you very much' },
    { source: 'おはようございます', translation: 'Good morning' },
    { source: '日本語は難しいです', translation: 'Japanese is difficult' },
  ],
  arabic: [
    { source: 'مرحبا', translation: 'Hello' },
    { source: 'شكراً جزيلاً', translation: 'Thank you very much' },
    { source: 'صباح الخير', translation: 'Good morning' },
    { source: 'كيف حالك؟', translation: 'How are you?' },
  ],
};

export const AKKADIAN_CACHED_TRANSLATIONS: Array<{ input: string; output: string }> = [
  { input: 'um-ma A-šùr-i-mì-tí-ma a-na Ṣú-ḫa-a-a qí-bi-ma', output: 'Thus says Ashur-imitti: speak to Tsukhaya' },
  { input: '1 ma-na KÙ.BABBAR ṣa-ru-pá-am', output: '1 mina of refined silver' },
  { input: 'a-na ha-ra-nim ú-ṣé-er', output: 'send on the caravan' },
];

// Phrase-level cache for languages whose HF models lack free-tier inference support.
// Keyed by lower-cased trimmed source text.
export const LANGUAGE_PHRASE_CACHE: Record<string, Record<string, string>> = {
  filipino: {
    'magandang umaga': 'Good morning',
    'magandang hapon': 'Good afternoon',
    'magandang gabi': 'Good evening',
    'salamat po': 'Thank you (polite)',
    'salamat': 'Thank you',
    'kumusta ka?': 'How are you?',
    'kumusta ka': 'How are you?',
    'mahal kita': 'I love you',
    'oo': 'Yes',
    'hindi': 'No',
    'paalam': 'Goodbye',
    'magkano ito?': 'How much is this?',
    'magkano ito': 'How much is this?',
    'hindi ko maintindihan': 'I do not understand',
    'nagsasalita ka ba ng ingles?': 'Do you speak English?',
    'nagsasalita ka ba ng ingles': 'Do you speak English?',
    'ang pangalan ko ay charles': 'My name is Charles',
    'saan ang banyo?': 'Where is the bathroom?',
    'saan ang banyo': 'Where is the bathroom?',
    'tulong!': 'Help!',
    'tulong': 'Help!',
    'masarap': 'Delicious',
    'maganda': 'Beautiful',
    'mabuti': 'Good / Fine',
    'paumanhin': 'Excuse me / Sorry',
  },
};

export const FRENCH_TRAINING_PAIRS = [
  { french: 'Bonjour', english: 'Hello' },
  { french: 'Merci', english: 'Thank you' },
  { french: 'Au revoir', english: 'Goodbye' },
  { french: 'Oui', english: 'Yes' },
  { french: 'Non', english: 'No' },
  { french: 'Comment allez-vous', english: 'How are you' },
  { french: 'Bonne nuit', english: 'Good night' },
  { french: 'Bonjour le monde', english: 'Hello world' },
  { french: "Je m'appelle", english: 'My name is' },
  { french: 'Merci beaucoup', english: 'Thank you very much' },
  { french: "S'il vous plaît", english: 'Please' },
  { french: "Je t'aime", english: 'I love you' },
  { french: 'Où est la gare', english: 'Where is the train station' },
  { french: 'Combien ça coûte', english: 'How much does it cost' },
  { french: "Je ne comprends pas", english: 'I do not understand' },
  { french: 'Parlez-vous anglais', english: 'Do you speak English' },
  { french: "C'est magnifique", english: 'It is magnificent' },
  { french: 'Bonne journée', english: 'Have a good day' },
  { french: 'Le chat est petit', english: 'The cat is small' },
  { french: 'La maison est grande', english: 'The house is big' },
  { french: "Il fait beau aujourd'hui", english: 'The weather is nice today' },
  { french: 'Je voudrais du café', english: 'I would like some coffee' },
  { french: 'Excusez-moi', english: 'Excuse me' },
  { french: "Je suis désolé", english: 'I am sorry' },
  { french: "C'est délicieux", english: 'It is delicious' },
];
